import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {GraphQLClient, gql} from 'graphql-request'
import { BlogCard } from '../components/BlogCard'

const graphcms = new GraphQLClient("https://api-ap-south-1.graphcms.com/v2/cl56mro663y7o01uee590bevl/master")

const QUERY = gql`
  {
    posts{
      title,
      datePublished,
      content{
        html
      },
      slug
      id,
      coverPhoto{
        url
      }
      author{
        name,
        avatar {
          url
        }
      }
    } 
  }
`

export async function getStaticProps(){
  const {posts} = await graphcms.request(QUERY);
  return{
    props: {
      posts,
    },
    revalidate: 60,
  };
}

export default function Home({posts}) {
  return (
    <div className='posts-section text-gray-400 w-9/12 mx-auto'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='main-posts text-gray-400 w-9/12 mx-auto'>
        <h1 className='text-center text-4xl font-mono py-10'>Cloud Writes</h1>
        {posts.map((post) => (
          <BlogCard key={post.id} {...post}/>
        ))}
      </main>
    </div>
  )
}
